### ISSUE TITLE
Themes not in sync?

### ISSUE THREAD

**Issue by s-n-g** [edunfelt/base16-pyradio#10]
Hi again @edunfelt 

I have started working on downloading the theme files...

The way I do it is I get the $BASE_THEME and create a URL:

https://raw.githubusercontent.com/edunfelt/base16-pyradio/master/themes/base16-**${BASE_THEME}**.pyradio-theme

The thing is that while "playing" with it, I got this:

```
requests failed: <Response [404]>
/home/spiros/.config/pyradio/themes/autoload_base16.pyradio-theme
https://raw.githubusercontent.com/edunfelt/base16-pyradio/master/themes/base16-heetch.pyradio-theme
```

Searching the `themes` directory, I see

```
╭─spiros@py ~/projects/base16-pyradio/themes  ‹em*› 
╰─➤  ls *hee*
base16-heetch-dark.pyradio-theme  base16-heetch-light.pyradio-theme
```

And

```
╭─spiros@py ~  
╰─➤  echo $BASE16_THEME
heetch
```
But
```
╭─spiros@py ~  
╰─➤  base16_heetch
base16_heetch        base16_heetch-light
```
This is zsh autocompletion

Themes are not in sync or something?
Do you have any idea?

BTW, my `base16_shell` is up to date...

```
╭─spiros@py ~/.config/base16-shell  ‹main› 
╰─➤  git remote -v
origin	https://github.com/base16-project/base16-shell.git (fetch)
origin	https://github.com/base16-project/base16-shell.git (push)
```

**Comment by edunfelt** [comment]
Looking at the schemes directory from the [go builder](https://github.com/base16-project/base16-builder-go) (which base16-shell seems to be using) it looks like it's pulling from [here](https://github.com/base16-project/base16-schemes/tree/0a6b24b22f48c8a786feebc973f233238eaaaecb). 

**However** base16-pyradio is pulling its schemes from [its main](https://github.com/base16-project/base16-schemes.git) instead, so there seems to be more recent commits? This is what is recommended in the README of the go builder. I'm not sure what the best way is to fix this, seems like a bad idea to pull a presumably outdated version of the schemes list. :thinking:

**Comment by edunfelt** [comment]
Now I notice that both those links have the `base16-heetch` and `base16-heetch-light` only though, and not the `base16-heetch-dark` found here. I have no idea why! :open_mouth:

**Comment by edunfelt** [comment]
Ah! I have a new theory now!

Looking at the scheme files [1](https://github.com/base16-project/base16-schemes/blob/0a6b24b22f48c8a786feebc973f233238eaaaecb/heetch.yaml) and [2](https://github.com/base16-project/base16-schemes/blob/main/heetch-light.yaml) I think it's possible that the node builder that we're using utilizes the `scheme` metadata to construct the file names, hence it adds that `dark` appendix to Heetch Dark even though the scheme file itself is only called `heetch`.

Furthermore, some schemes which might have special characters in the name - such as [Rosé Pine](https://github.com/base16-project/base16-schemes/blob/main/rose-pine.yaml) simply gets renamed to [ros-pine](https://github.com/edunfelt/base16-pyradio/blob/main/themes/base16-ros-pine.pyradio-theme) by the builder.

---

*edit:* We can see [here](https://github.com/base16-project/base16-shell/blob/1af738dbb8fb6dbfd0402502ed47937ef4ebd461/templates/default.mustache#L5) that the base16-shell is setting the env variable to the `scheme-slug`. 

Here is more information about all of this: https://github.com/base16-project/base16/blob/main/builder.md#template-variables

**Comment by s-n-g** [comment]
Wow!
That's a lot for my aging brain (and eyes) :blush:

ok, some of the themes will not work, for now, I don't know what else to say :grin:

But I have a bigger problem right now...

Using the `$BASE16_THEME` variable wil not do, as it's terminal specific...
I mean, imagine I am running `pyradio` in one terminal (with any given theme).
Then I change the theme in another terminal.
The first one will know nothing about it :innocent: and no theme auto-update can occur... 

I was thinking of asking them to include a `echo "$BASE16_THEME" > ~/.config/base-shell/last-theme` or something, but that is not easy to do; these variables do not support the PATH...

I don't know...

**Comment by s-n-g** [comment]
ok, just found out about the aliases :)

This is feasible, instead of 
```
alias base16_zenburn='_base16 "/home/spiros/.config/base16-shell/scripts/base16-zenburn.sh" zenburn'
```
we could have 
```
alias base16_zenburn='_base16 "/home/spiros/.config/base16-shell/scripts/base16-zenburn.sh" zenburn && echo zenburn > ~/.config/base16_last_theme
```

I saw a `profile.sh` or something...

#### EDIT
https://github.com/base16-project/base16-shell/blob/main/profile_helper.sh
and 
https://github.com/base16-project/base16-shell/blob/main/profile_helper.fish

I can create a PR for the first one, but for `fish`, for the love of God, what are they doing in there?

**Comment by edunfelt** [comment]
> ok, some of the themes will not work, for now, I don't know what else to say grin

I could open an issue about this in the builder repo, as I assume there is where the problem lies and it's probably better for everyone if the built themes have the same names from all builders. I'm quite busy at the moment though, but I'll do it as soon as I have time to properly sit down with this 


> I can create a PR for the first one, but for `fish`, for the love of God, what are they doing in there?

Good idea! Also, the `fish` thing I don't know anything about that... 😵

**Comment by s-n-g** [comment]
> > ok, some of the themes will not work, for now, I don't know what else to say grin
> 
> I could open an issue about this in the builder repo, as I assume there is where the problem lies and it's probably better for everyone if the built themes have the same names from all builders. I'm quite busy at the moment though, but I'll do it as soon as I have time to properly sit down with this

Yes, that would be so kind of you!
I would not know where to start... :blush:
And don't worry about the time... we already have 230-something themes!  :partying_face:

> 
> > I can create a PR for the first one, but for `fish`, for the love of God, what are they doing in there?
> 
> Good idea! Also, the `fish` thing I don't know anything about that... dizzy_face

Yes, me neither!
I will try to read a bit about it...

So... later! :)

**Comment by s-n-g** [comment]
Just created this PR: https://github.com/base16-project/base16-shell/pull/5

**Comment by edunfelt** [comment]
I opened an issue about it now @s-n-g, we'll see how it goes or I might have misunderstood how it works: :)

**Comment by s-n-g** [comment]
BTW, my PR got closed...

It seems there is a `~/.config/base16-project/base16_shell_theme` symlink to the last used theme that we did not know about!
I'm working on it!

**Comment by s-n-g** [comment]
@edunfelt based on https://github.com/base16-project/base16-builder-node/issues/9#issuecomment-1178727191 can you please update the themes?

I can't :)

```
╭─spiros@py ~  
╰─➤  ./make-base16-pyradio
Cloning into 'base16-pyradio'...
remote: Enumerating objects: 1012, done.
remote: Counting objects: 100% (1012/1012), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 1012 (delta 961), reused 961 (delta 927), pack-reused 0
Receiving objects: 100% (1012/1012), 227.07 KiB | 431.00 KiB/s, done.
Resolving deltas: 100% (961/961), done.
rm -rf ../../schemes
git clone https://github.com/base16-project/base16-schemes.git ../../schemes
Cloning into '../../schemes'...
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 275 (delta 35), reused 246 (delta 24), pack-reused 0
Receiving objects: 100% (275/275), 64.29 KiB | 1.00 MiB/s, done.
Resolving deltas: 100% (35/35), done.
cd ../../.. && base16 build
error: missing required argument 'path'
make: *** [Makefile:15: build] Error 1




╭─spiros@py ~  
╰─➤  cat make-base16-pyradio
#!/bin/bash
[ -d base16 ] && rm -rf base16
mkdir -p base16/templates && cd base16/templates
git clone git@github.com:edunfelt/base16-pyradio.git
cd base16-pyradio
make
```

**Comment by edunfelt** [comment]
@s-n-g Updated! The names look better now - awesome!
