### ISSUE TITLE
Old comment...

### ISSUE THREAD

**Issue by s-n-g** [edunfelt/base16-pyradio#3]
Just transferring the comment from https://github.com/coderholic/pyradio/issues/159#issuecomment-1173155647 so that we do not have to go back and forth :)

Hi @edunfelt 

I haven't tested anything yet; just got back from a family feast and I'm still a bit under the weather :wink: 

But I've seen the work you've done; it's impressive especially in such short time :astonished:

Just two things...

With v. `0.8.9.22`, the name of the theme can be anything we want... the name `auto` was just a test case... I would propose something like `base16` of `base16_pyradio` or something like that...

Before answering your question about the transparency thing, I'd like to understand just how base16 would work...

What I would expect from it is to

1. give it an output filename (for example, `~/.config/pyradio/base16.pyradio-theme`)
2. upon acceptance of the filename, it  (base16, that is) would create the file (or update it if it already exists)...
3. set pyradio to watch `~/.config/pyradio/base16.pyradio-theme`
4. enable a theme, for example `base16_cupcake` from a terminal
5. have it (base16, that is) update  `~/.config/pyradio/base16.pyradio-theme` using the base16-pyradio template, which would force pyradio to "reapply" the theme...

Is this what `base16` will do?

#### EDIT

Now, about the transparency thing...

Does the theme generating script (probably `base16-builder-python`) know anything about the theme's background color?

What I mean is, the way transparency works for pyradio, it makes no sense to have the transparency on with a "light" theme, it will probably look just plain ugly... But if the theme's background is black (well, dark or close to black) the theme will probably look good either way.

So, if the generating script can make the distinction, it might be possible to have a transparency hint value of 2 (or even 1), otherwise you could just leave the transparency part st it currently is.

And, no, there would be no reason to create a second template just to have a different value of the transparency hint...

**Comment by edunfelt** [comment]
Hi again! :)

> Is this what `base16` will do?

Well, I think the [builder](https://github.com/base16-project/base16-builder-node) only has the option to build all theme files currently, and not a specific one. It takes as input the template files and spits out a bunch of `.pyradio-theme`-files after injecting the correct hex-values based on the `baseXX` color names given in scheme files [found here](https://github.com/base16-project/base16-schemes).

So I don't think this is something that should (or could?) be smoothly implemented in this repo - but perhaps in [coderholic/pyradio](https://github.com/coderholic/pyradio), if I understand correctly.

Why not add some neat script to pyradio which fetches a theme chosen by the user and copies the contents of the corresponding file `themes/*.pyradio-theme` from this repo into the local `base16` theme-file? Something similar to the usual [installation instructions](https://github.com/edunfelt/base16-pyradio#install-a-theme=).

The theme files in this repo should be in sync with the official base16 schemes using github actions (I still need to update this now btw after the switch from pybase16 builder...).



> Does the theme generating script (probably `base16-builder-python`) know anything about the theme's background color?

No. So probably hard to implement at this stage. Some light themes have the `-light` appendix but I don't think we can count on it at this point as there is no such standard naming convention in base16 to my knowledge.

**Comment by s-n-g** [comment]
>> Does the theme generating script (probably base16-builder-python) know anything about the theme's background color?

> No. So probably hard to implement at this stage. Some light themes have the `-light` appendix but I don't think we can count on it at this point as there is no such standard naming convention in base16 to my knowledge.

Yes, I've seen that too... Not reliable. unfortunately...
For example your favorite theme (cupkace) is a light theme, but no `-light` in the filename :(
So, we'd better stick to the `transparency 0` just to be on the safe side :wink:

**Comment by s-n-g** [comment]
> Why not add some neat script to pyradio which fetches a theme chosen by the user and copies the contents of the corresponding file `themes/*.pyradio-theme` from this repo into the local `base16` theme-file? Something similar to the usual [installation instructions](https://github.com/edunfelt/base16-pyradio#install-a-theme=).

Sure. that's feasible, but that is not the point...
I was hoping we could have something that would need no user action other than `base16_cupkace` (for example) in a terminal...

Does `base16` save the last used theme anywhere?
I see a `~/.config/base16-shell` but no config file

**Comment by edunfelt** [comment]
I have updated the workflow now to keep the themes in sync! :)

> I was hoping we could have something that would need no user action other than base16_cupkace (for example) in a terminal...

Agreed.

> Does `base16` save the last used theme anywhere?

That file might be from the [base16-shell](https://github.com/base16-project/base16-shell), but I'm not sure. I don't have it installed currently, but from their readme it seems as though the current theme would be stored in the `BASE16_THEME` environment variable.

**Comment by s-n-g** [comment]
> That file might be from the [base16-shell](https://github.com/base16-project/base16-shell), but I'm not sure. I don't have it installed currently, but from their readme it seems as though the current theme would be stored in the `BASE16_THEME` environment variable.

Yes!
Thank you!
I can work with that!

```
╭─spiros@py ~/.config/base16-shell  ‹master› 
╰─➤  echo $BASE16_THEME        
summerfruit-dark
╭─spiros@py ~/.config/base16-shell  ‹master› 
╰─➤  base16_cupcake 
╭─spiros@py ~/.config/base16-shell  ‹master› 
╰─➤  echo $BASE16_THEME        
cupcake
```

**Comment by s-n-g** [comment]
Hey @edunfelt 

Just submitted a last minute PR.

After this one, I think we are ready to go on and submit the whole thing to base16... unless there's something else you feel needs attention...

If, you agree, you just go on and do your magic :wink: with base16, and I will start thinking about how to integrate the whole thing to pyradio :)

BTW, the URL pointing to the files found in the README, is it the final one? I mean can I use it to get the files after they have been submitted to base16?

**Comment by edunfelt** [comment]
Hi @s-n-g!

Awesome! :tada: 

Thank you so so much for looking things over and for all the great suggestions - it's nice to see pyradio with so many new and pretty themes. I think it was already a year ago or so that we originally discussed base16 themes, and your newest changes to pyradio made it all possible! :)

Nothing really changes, this is the repo where the template and generated themes will live and for now there is just a link from the main base16 repo ([it's now listed under "Other"](https://github.com/base16-project/base16#unofficial-templates)). So the links will all point to here. I asked them on irc if the template should be added as a contrib or unofficial template and they said unofficial while they're still figuring things out with the new org.

I'll close this issue for now, feel free to open new ones or submit PRs if anything else I can do comes up in the future!
